### PR TITLE
FreeBSD build fixes and cleanups

### PR DESCRIPTION
**Pull request by q66**
These are definitely harmless, and enable building on FreeBSD, though I'm still not sure whether the generated images are correct for the Pixel C. If they are not, then the fault is somewhere within the util itself, though.

### CODE REVIEW

**Comment by q66** [comment]
I just checked, the signed image is the same as the one signed with the Linux version, so it's safe.

```
q66@banana: /usr/home/q66/smaug-kern/kerngen$ sha256 boot-futility-freebsd.img
SHA256 (boot-futility-freebsd.img) = 97dff2a2b45a3c7ba5cecf2da581e21acde9610e91f2563bee8396aa69e62a08
q66@banana: /usr/home/q66/smaug-kern/kerngen$ sha256 boot-futility-linux.img 
SHA256 (boot-futility-linux.img) = 97dff2a2b45a3c7ba5cecf2da581e21acde9610e91f2563bee8396aa69e62a08
```

**Comment by osm0sis** [comment]
Whoa, these are looking pretty hack-and-slash... The HAVE_MACOS thing actually needs to stay to support cross-compiling to Darwin.

**Comment by q66** [comment]
The sources have been updated to cross-compile cleanly to all targets.

HAVE_MACOS was there pretty much to disable some Linux-specific features, and wasn't necessarily for Mac OS; therefore, I have replaced the relevant `ifndef HAVE_MACOS` stuff with `ifdef __linux__` or whatever was suitable at each place, so HAVE_MACOS now serves no purpose, as only standard macros are used.

As for cgpt, it was left over from the vboot reference tools but wasn't actually used, so I ditched it as it contained some unnecessary Linux-specific code; libcgpt, which actually contains stuff that is used in futility, is kept.

**Comment by q66** [comment]
see:

```
q66@banana: /home/q66/smaug-kern/repos/futility$ find . -name '*.c'|xargs grep HAVE_MACOS
q66@banana: /home/q66/smaug-kern/repos/futility$ find . -name '*.h'|xargs grep HAVE_MACOS
q66@banana: /home/q66/smaug-kern/repos/futility$ 
```

If anything, the tool can actually target *more* systems than it did before, no compatibility was broken.

**Comment by q66** [comment]
You can also check https://github.com/osm0sis/futility/pull/1/commits/181e114ffd42460ed0888749bf78d3207470ce99 for how `HAVE_MACOS` was replaced.

**Comment by osm0sis** [comment]
Fair enough. The uname stuff in the Makefiles however does need to stay, since it needs to recognize both native MacOS compiles and a MacOS cross-compile from, say, Cygwin.

**Comment by q66** [comment]
Ah, fair. I updated the commit.

**Comment by osm0sis** [comment]
Thanks! Missed libvboot_util/Makefile though. Then you'll have to give me a few days (free time is tight for me right now) to try it out on my build platforms to make sure all is still good.

**Comment by q66** [comment]
Haven't missed it, if you look at it, all it does when cross-compiling for Darwin is add `HAVE_MACOS`, which is not necessary anymore in the first place. In the main Makefile it actually does something platform-relevant.

**Comment by q66** [comment]
Also, no worries about the merging - I have the repo forked into the pixelc-linux organization for our own use.

**Comment by osm0sis** [comment]
Nah, please check again, it also has the uname_s stuff for the cross-compilation, which needs to stay:

```
-ifneq (,$(findstring darwin,$(CROSS_COMPILE)))
-    UNAME_S := Darwin
-else
-    UNAME_S := $(shell uname -s)
-endif
```

With your changes only the ifeq following that which sets HAVE_MACOS would be what we'd want to chop out.

**Comment by q66** [comment]
Take a look at that diff again - `UNAME_S` was only used right afterwards, to add `HAVE_MACOS` into `CFLAGS`, after removal of that there was no more use for `UNAME_S`.

Check this out:

```
q66@banana: /home/q66/smaug-kern/repos/futility$ find . -type f|xargs grep UNAME_S
./Makefile:    UNAME_S := Darwin
./Makefile:    UNAME_S := $(shell uname -s)
./Makefile:ifeq ($(UNAME_S),Darwin)
```

`UNAME_S` is only ever used in the Makefiles, and the only remaining use is in the primary Makefile.

In the Makefile where I removed it, it was only used in this conditional

```
ifeq ($(UNAME_S),Darwin)
    CFLAGS += -DHAVE_MACOS
endif
```

Since `HAVE_MACOS` was made unnecessary, there was no more need for the `UNAME_S` either.

**Comment by osm0sis** [comment]
Oh wait, I see now. You mean the dead strip, etc. Whereas nothing else happens in the lib. Gotcha gotcha. Sorry, doing too many things at once here.

Edit: Haha yup, sorry, saw it myself before you replied.

**Comment by q66** [comment]
Yeah. It'd be nice to have `--gc-sections` supported in the Mac OS linker, so that the additional check can be removed as well, but sadly they use a different executable format than other Unix-likes, so the linker infra is going to be different. Other targets (Linux and FreeBSD, and others) all support `--gc-sections`.

**Comment by osm0sis** [comment]
Got the chance to test it out, working great across Cygwin, and Linux, MacOS and NDK cross-compilers! Thanks!

**Pull request merged**
